Control Plane Logs Collection for OCNE and Standalone Kubernetes Clusters
oracle-quickstart/oci-kubernetes-monitoring pull request #56
Opened 2023-11-06 05:34 UTC by naga-barri

2023-11-06 09:52 UTC, santhoshkvuda submitted a review, later dismissed

2023-11-06 09:53 UTC, palukuri approved these changes

2023-11-08 17:13 UTC, kgvarun requested changes

2023-11-08 17:13 UTC, kgvarun commented on CHANGELOG.md
> +- Support for launching Fluentd containers in privileged mode (default false).
Is this for both DS and RS?

2023-11-08 17:13 UTC, kgvarun commented on charts/logan/values.yaml
> +# In some special Kubernetes environments where SELinux mode is enforcing, we require this flag to be set to ture
Suggest rephrasing:
"Default: 'false'. This is not a required for OKE clusters. In Kubernetes environments where SELinux mode is enforced, set this flag to 'true' to allow fluentd pods to access log files.”

2023-11-08 17:13 UTC, kgvarun commented on docs/FAQ.md
> +#### How to fix _execution expired_ error ?
Pls add where might users see this error message.

2023-11-08 17:13 UTC, kgvarun commented on docs/FAQ.md
> +### Log Collection for OCNE (Oracle Cloud Native Environment)
On all troubleshoot related faqs pls add the location of files/etc where users might see these error messages.

2023-11-09 11:25 UTC, naga-barri commented on CHANGELOG.md
> +- Support for launching Fluentd containers in privileged mode (default false).
Yes

2023-11-14 18:50 UTC, kgvarun approved these changes

2023-11-15 07:33 UTC, palukuri approved these changes

2023-11-15 12:38 UTC, santhoshkvuda approved these changes

2023-11-15 12:39 UTC, merged